version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ["sh", "docker-entrypoint.sh"]

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
