version: "3.8"

services:
    frontend:
        build: ./frontend
        ports: 
            - 3000:3000
        volumes: 
            - ./frontend:/app
    backend:
        build: ./backend
        ports:
            - 3001:3001
        environment:
            - DB_URL=mongodb://database/vidly
        volumes: 
            - ./backend:/app
        command: ["sh", "docker-entrypoint.sh"]
    database:
        image: mongo:4.0-xenial
        ports: 
            - 27018:27017
        volumes:
            - vidly:/data/db

volumes:
    vidly:

